# Generated by Django 4.0.5 on 2022-07-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='altarnative_products',
            field=models.ManyToManyField(blank=True, null=True, through='source.AltarnativeProduct', to='source.product'),
        ),
    ]
