# Generated by Django 4.0.5 on 2022-07-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0004_alter_product_altarnative_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='altarnative_products',
            field=models.ManyToManyField(blank=True, through='source.AltarnativeProduct', to='source.product'),
        ),
    ]
