# Generated by Django 4.0.5 on 2022-07-08 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0006_material_cas_no_material_created_at_material_ec_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
