# Generated by Django 4.0.5 on 2022-09-17 12:46

from django.conf import settings
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('source', '0008_alter_material_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='rozets',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('PESTICIDES_FREE', 'Tarım ilacı içermez'), ('TRANS_OIL_FREE', 'Trans yağ içermez'), ('GLUTEN_FREE', 'Gluten içermez'), ('NON_TOXIC', 'Toksik değildir'), ('PARABEN_FREE', 'Paraben içermez')], max_length=200),
        ),
    ]
